### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by ivanvzqzz** [ivanvzqzz/skills-communicate-using-markdown#2]
# Aquí vamos a crear una checklist:

- [x] Se hizo el curso Introduction to GitHub.
- [ ] Se hizo el curso Communicate using Markdown.
- [ ] Se entregó la tarea al Dr. Julio Waissman.
